name: Train Model with MLflow

on:
  push:
    paths:
      - MLProject/**
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        environment-file: MLProject/conda.yaml
        activate-environment: travel-insurance-env

    - name: Install MLflow
      run: pip install mlflow

    - name: Run MLproject
      run: mlflow run . --env-manager=local

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/trained_model.pkl

    - name: Upload MLflow logs
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: mlruns/

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        mlflow models build-docker -m MLProject/model -n NiaPutri23/travel-insurance
        docker push NiaPutri23/travel-insurance
