name: Train Model with MLflow

on:
  push:
    paths:
      - MLProject/**
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.7

    - name: Check Environment
      run: python --version && pip --version && mlflow --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r MLProject/requirements.txt
        pip install mlflow

    - name: Run MLflow project
      working-directory: MLProject
      run: mlflow run . --env-manager=local

    - name: Get latest MLflow run_id
      working-directory: MLProject
      run: |
        RUN_ID=$(mlflow runs list --experiment-id 0 --order-by attribute.start_time DESC --max-results 1 --output json | jq -r '.[0].run_id')
        echo "Latest run_id: $RUN_ID"
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/trained_model.pkl

    - name: Upload MLflow logs
      uses: actions/upload-artifact@v4
      with:
        name: mlruns
        path: MLProject/mlruns
